[project]
name = "machine-learning-tutorial"
version = "0.1.0"
description = "In this project I learn the basics of machine learning using Python."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.5",
    "pandas>=2.3.3",
]
